#!/usr/bin/env python3
"""Build (do not apply) SQL to load Gemini issue descriptions from local/work.

Usage:
  python3 db/migration/issue_gemini_descriptions/build.py
  python3 db/migration/issue_gemini_descriptions/build.py --only-empty
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
WORK = Path(os.environ.get("ZXPRESS_ISSUE_DESC_WORK", str(ROOT / "local" / "work")))
OUT = HERE / "generated"

MYSQL_CONTAINER = os.environ.get("ZXPRESS_MYSQL_CONTAINER", "zxpress_db")
MYSQL_USER = os.environ.get("DB_USER") or os.environ.get("MYSQL_USER", "zxpress_u")
MYSQL_PASS = os.environ.get("DB_PASS") or os.environ.get("MYSQL_PASSWORD", "changeme-app-password")
MYSQL_DB = os.environ.get("DB_NAME") or os.environ.get("MYSQL_DATABASE", "zxpress_db")

KEYS = (
    "description_ru",
    "description_en",
    "meta_description_ru",
    "meta_description_en",
)
META_MAX = 512
FILE_RE = re.compile(r"^issue-desc-(\d+)\.json$")


def sql_str(s: str) -> str:
    return "'" + s.replace("\\", "\\\\").replace("'", "''") + "'"


def clean_text(s: str) -> str:
    """Drop C0 controls (e.g. \\x08 from Gemini) except tab/newline; collapse spaces."""
    s = "".join(ch for ch in str(s) if ord(ch) >= 32 or ch in "\t\n")
    return re.sub(r"\s+", " ", s).strip()


def clip_meta(s: str) -> str:
    s = clean_text(s)
    if len(s) > META_MAX:
        s = s[:META_MAX].rstrip(" .,;:-")
    return s


def load_jsons(work: Path) -> list[dict]:
    rows: list[dict] = []
    for path in sorted(work.glob("issue-desc-*.json"), key=lambda p: p.name):
        m = FILE_RE.match(path.name)
        if not m:
            continue
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as e:
            print(f"skip bad JSON {path.name}: {e}", file=sys.stderr)
            continue
        issue_id = int(data.get("issue_id") or m.group(1))
        if issue_id <= 0:
            continue
        vals = {}
        ok = True
        for k in KEYS:
            v = clean_text(data.get(k) or "")
            if not v:
                ok = False
                break
            vals[k] = clip_meta(v) if k.startswith("meta_") else v
        if not ok:
            print(f"skip incomplete {path.name}", file=sys.stderr)
            continue
        rows.append({"issue_id": issue_id, "file": path.name, **vals})
    rows.sort(key=lambda r: r["issue_id"])
    return rows


def docker_mysql(sql: str) -> str:
    cmd = [
        "docker",
        "exec",
        MYSQL_CONTAINER,
        "mysql",
        "-N",
        f"-u{MYSQL_USER}",
        f"-p{MYSQL_PASS}",
        MYSQL_DB,
        "-e",
        sql,
    ]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        raise SystemExit(f"mysql failed: {r.stderr or r.stdout}")
    return "\n".join(
        ln
        for ln in r.stdout.splitlines()
        if ln and not ln.startswith("mysql: [Warning]")
    )


def filter_only_empty(rows: list[dict]) -> list[dict]:
    """Keep rows where all four description fields are empty in DB."""
    if not rows:
        return []
    ids = [str(r["issue_id"]) for r in rows]
    # chunk IN lists
    empty_ids: set[int] = set()
    chunk = 400
    for i in range(0, len(ids), chunk):
        part = ",".join(ids[i : i + chunk])
        raw = docker_mysql(
            "SELECT id FROM issue WHERE id IN ("
            + part
            + ") AND TRIM(IFNULL(description_ru,''))='' "
            + "AND TRIM(IFNULL(description_en,''))='' "
            + "AND TRIM(IFNULL(meta_description_ru,''))='' "
            + "AND TRIM(IFNULL(meta_description_en,''))=''"
        )
        for line in raw.splitlines():
            if line.strip().isdigit():
                empty_ids.add(int(line.strip()))
    return [r for r in rows if r["issue_id"] in empty_ids]


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--work", type=Path, default=WORK)
    ap.add_argument(
        "--only-empty",
        action="store_true",
        help="Only issues with empty description_* / meta_description_* in DB",
    )
    args = ap.parse_args()
    work = args.work.resolve()
    if not work.is_dir():
        raise SystemExit(f"Not a directory: {work}")

    rows = load_jsons(work)
    total_files = len(rows)
    if args.only_empty:
        rows = filter_only_empty(rows)

    OUT.mkdir(parents=True, exist_ok=True)
    sql_path = OUT / "01_update_issue_descriptions.sql"
    lines: list[str] = [
        "-- Generated by issue_gemini_descriptions/build.py — DO NOT hand-edit",
        f"-- {datetime.now(timezone.utc).isoformat()}",
        f"-- source: {work}",
        f"-- updates: {len(rows)} (from {total_files} JSON files"
        + (", only-empty" if args.only_empty else ", overwrite all four fields")
        + ")",
        "SET NAMES utf8mb4;",
        "START TRANSACTION;",
        "",
    ]

    for r in rows:
        lines.append(
            "UPDATE issue SET "
            f"description_ru={sql_str(r['description_ru'])}, "
            f"description_en={sql_str(r['description_en'])}, "
            f"meta_description_ru={sql_str(r['meta_description_ru'])}, "
            f"meta_description_en={sql_str(r['meta_description_en'])} "
            f"WHERE id={int(r['issue_id'])} LIMIT 1;"
        )

    lines.append("")
    lines.append("COMMIT;")
    sql_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    summary = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "work_dir": str(work),
        "json_files": total_files,
        "updates": len(rows),
        "only_empty": bool(args.only_empty),
        "sql": str(sql_path.relative_to(ROOT)),
        "issue_id_min": rows[0]["issue_id"] if rows else None,
        "issue_id_max": rows[-1]["issue_id"] if rows else None,
        "note": "Not applied. Run apply.py when ready.",
    }
    (OUT / "summary.json").write_text(
        json.dumps(summary, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    print(f"Wrote {sql_path} ({sql_path.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
