CREATE TABLE letters (
    id           INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    author_from  INT UNSIGNED NOT NULL,
    author_to    INT UNSIGNED NOT NULL,
    title_ru     VARCHAR(255) NOT NULL,
    title_en     VARCHAR(255) NOT NULL,
    slug_ru      VARCHAR(191) CHARACTER SET ascii COLLATE ascii_general_ci DEFAULT NULL,
    slug_en      VARCHAR(191) CHARACTER SET ascii COLLATE ascii_general_ci DEFAULT NULL,
    summary_ru   TEXT DEFAULT NULL,
    summary_en   TEXT DEFAULT NULL,
    body_ru      TEXT DEFAULT NULL,
    body_en      TEXT DEFAULT NULL,
    date         DATE DEFAULT NULL,
    view_count   INT UNSIGNED DEFAULT 0,
    is_active    TINYINT(1) DEFAULT 1,
    publish_status TINYINT UNSIGNED NOT NULL DEFAULT 2, -- 0=draft 1=queued 2=published 3=deleted
    queued_at    DATETIME NULL DEFAULT NULL,
    published_at DATETIME NULL DEFAULT NULL,
    deleted_at   DATETIME NULL DEFAULT NULL,
    created_at   DATETIME DEFAULT CURRENT_TIMESTAMP,
    meta_description_ru VARCHAR(512) DEFAULT NULL,
    meta_description_en VARCHAR(512) DEFAULT NULL,

    KEY idx_letters_publish_queue (publish_status, queued_at, id),
    KEY idx_letters_published_at (published_at),
    UNIQUE KEY uq_letters_slug_ru (slug_ru),
    UNIQUE KEY uq_letters_slug_en (slug_en),
    FOREIGN KEY (author_from) REFERENCES authors(id) ON DELETE RESTRICT,
    FOREIGN KEY (author_to)   REFERENCES authors(id) ON DELETE RESTRICT
);
