CREATE TABLE `periodical_articles` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `issue_id` int unsigned NOT NULL,
  `original_language_id` int DEFAULT NULL,
  `language_id` int NOT NULL,
  `title_ru` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `title_en` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `abstract_ru` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `abstract_en` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `text_ru` mediumtext COLLATE utf8mb4_unicode_ci,
  `text_en` mediumtext COLLATE utf8mb4_unicode_ci,
  `page_start` smallint unsigned DEFAULT NULL,
  `page_end` smallint unsigned DEFAULT NULL,
  `sort_order` smallint unsigned NOT NULL DEFAULT '0',
  `views` int unsigned NOT NULL DEFAULT '0',
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `meta_description_ru` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `meta_description_en` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_issue` (`issue_id`),
  KEY `idx_original_language` (`original_language_id`),
  KEY `idx_language` (`language_id`),
  CONSTRAINT `fk_article_issue` FOREIGN KEY (`issue_id`) REFERENCES `periodical_issues` (`id`),
  CONSTRAINT `fk_article_language` FOREIGN KEY (`language_id`) REFERENCES `languages` (`id`),
  CONSTRAINT `fk_article_original_language` FOREIGN KEY (`original_language_id`) REFERENCES `languages` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=482 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
