#!/usr/bin/env python3
"""Build (do not apply) idempotent SQL + file manifest for ZX-Ревю files from vtrd.in.

Does not write to DB. Usage:
  python3 db/migration/vtrd_revue_files/build.py
"""

from __future__ import annotations

import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
OUT = HERE / "generated"
MAPPING = HERE / "mapping.json"
SOURCE = "migration:vtrd_revue_files"
DEFAULT_FILES = Path(
    os.environ.get(
        "ZXPRESS_VTRD_FILES_DIR",
        str(ROOT / "local" / "work" / "vtrd-books"),
    )
)


def sql_str(s: str) -> str:
    return "'" + s.replace("\\", "\\\\").replace("'", "''") + "'"


def plural_ru(n: int, one: str, few: str, many: str) -> str:
    n_abs = abs(n) % 100
    n1 = n_abs % 10
    if 10 < n_abs < 20:
        return many
    if n1 == 1:
        return one
    if 2 <= n1 <= 4:
        return few
    return many


def main() -> None:
    files_dir = Path(DEFAULT_FILES)
    if not MAPPING.is_file():
        raise SystemExit(f"Missing {MAPPING}")
    raw = json.loads(MAPPING.read_text(encoding="utf-8"))
    mapping = {int(k): str(v) for k, v in raw.items()}

    items: list[dict] = []
    missing: list[str] = []
    for book_id in sorted(mapping):
        fname = mapping[book_id]
        src = files_dir / fname
        if not src.is_file() or src.stat().st_size < 1000:
            missing.append(f"{book_id}\t{fname}\t{src}")
            continue
        size_kb = max(1, (src.stat().st_size + 999) // 1000)
        items.append(
            {
                "book_id": book_id,
                "file_name": fname,
                "size_kb": size_kb,
                "bytes": src.stat().st_size,
                "src": str(src),
            }
        )

    if missing:
        print(f"WARN: {len(missing)} files missing under {files_dir}", file=sys.stderr)
        for m in missing:
            print(f"  {m}", file=sys.stderr)
    if not items:
        raise SystemExit("No files to migrate — download into FILES_DIR first")

    n = len(items)
    word_ru = plural_ru(n, "файл", "файла", "файлов")
    summary_ru = f"+{n} {word_ru}"
    summary_en = f"+{n} {'file' if n == 1 else 'files'}"
    title_ru = "ZX-Ревю: файлы выпусков"
    title_en = "ZX-Revue: issue files"

    OUT.mkdir(parents=True, exist_ok=True)
    sql_path = OUT / "01_books_files_activity.sql"
    man_path = OUT / "copy_manifest.tsv"
    sum_path = OUT / "summary.json"
    miss_path = OUT / "missing.txt"

    lines: list[str] = [
        f"-- Generated by vtrd_revue_files/build.py — DO NOT hand-edit",
        f"-- source={SOURCE}",
        f"-- files={n} from {files_dir}",
        f"-- generated_at={datetime.now(timezone.utc).isoformat()}",
        "-- Idempotent: skips books that already have books_files rows;",
        "-- skips activity rows that already exist for the same file id.",
        "SET NAMES utf8mb4;",
        "SET @now = UNIX_TIMESTAMP();",
        # Match activity_batch.source collation (avoid utf8mb4_0900_ai_ci mix).
        f"SET @src = CONVERT({sql_str(SOURCE)} USING utf8mb4) COLLATE utf8mb4_unicode_ci;",
        "",
        "-- One public batch for the whole import (reuse if present).",
        "INSERT INTO activity_batch (",
        "  created_at, closed_at, actor_user_id, domain, root_type, root_id,",
        "  title_ru, title_en, url_ru, url_en, summary_ru, summary_en, thumb_url,",
        "  items_count, public_items_count, is_public, source",
        ") ",
        "SELECT @now, @now, 0, 'book', 'book', 0,",
        f"  {sql_str(title_ru)}, {sql_str(title_en)}, '/ru/books', '/en/books',",
        f"  {sql_str(summary_ru)}, {sql_str(summary_en)}, NULL,",
        f"  {n}, {n}, 1, @src",
        "FROM DUAL",
        "WHERE NOT EXISTS (SELECT 1 FROM activity_batch WHERE source=@src LIMIT 1);",
        "",
        "SET @batch_id = (",
        "  SELECT id FROM activity_batch WHERE source=@src ORDER BY id DESC LIMIT 1",
        ");",
        "",
    ]

    for it in items:
        bid = it["book_id"]
        fn = it["file_name"]
        skb = it["size_kb"]
        lines += [
            f"-- book {bid} ← {fn}",
            "INSERT INTO books_files (",
            "  book_id, file_name, file_type, author, downloads, file_size, comment, upload_date",
            ") ",
            "SELECT ",
            f"  {bid}, {sql_str(fn)}, 0, 'vtrd.in', 0, {skb},",
            "  'import from https://vtrd.in/book.php', @now",
            "FROM DUAL",
            f"WHERE NOT EXISTS (SELECT 1 FROM books_files WHERE book_id={bid} LIMIT 1);",
            "",
            "UPDATE books b",
            "JOIN books_files bf",
            f"  ON bf.book_id=b.id AND bf.file_name={sql_str(fn)}",
            "SET b.file_id=bf.id",
            f"WHERE b.id={bid}",
            "  AND (b.file_id=0 OR b.file_id IS NULL OR b.file_id<>bf.id);",
            "",
            "INSERT INTO activity (",
            "  batch_id, created_at, actor_user_id, verb, object_type, object_id,",
            "  parent_type, parent_id, action, event_scope, is_public,",
            "  title_ru, title_en, url_ru, url_en, thumb_url, meta_json,",
            "  legacy_log_id, legacy_log_type",
            ") ",
            "SELECT",
            "  @batch_id, @now, 0, 'uploaded', 'book_file', bf.id,",
            f"  'book', {bid}, 'book_file.uploaded', 'content', 1,",
            f"  b.title1, b.title1, CONCAT('/ru/books/', {bid}), CONCAT('/en/books/', {bid}),",
            "  NULL,",
            "  JSON_OBJECT(",
            "    'source', @src,",
            "    'file_name', bf.file_name,",
            "    'file_id', bf.id,",
            f"    'id_press', {bid},",
            "    'id_screen', bf.id",
            "  ),",
            "  NULL, 101",
            "FROM books_files bf",
            f"JOIN books b ON b.id={bid}",
            f"WHERE bf.book_id={bid} AND bf.file_name={sql_str(fn)}",
            "  AND @batch_id IS NOT NULL",
            "  AND NOT EXISTS (",
            "    SELECT 1 FROM activity a",
            "    WHERE a.action='book_file.uploaded'",
            "      AND a.object_id=bf.id",
            f"      AND a.parent_id={bid}",
            "    LIMIT 1",
            "  );",
            "",
        ]

    lines += [
        "-- Refresh batch counters / summary from actual events.",
        "UPDATE activity_batch b",
        "JOIN (",
        "  SELECT batch_id, COUNT(*) AS c",
        "  FROM activity",
        "  WHERE batch_id=@batch_id",
        "  GROUP BY batch_id",
        ") x ON x.batch_id=b.id",
        "SET b.items_count=x.c,",
        "    b.public_items_count=x.c,",
        "    b.is_public=1,",
        "    b.closed_at=@now,",
        "    b.summary_ru=CONCAT('+', x.c, ' ',",
        "      CASE",
        "        WHEN x.c % 100 BETWEEN 11 AND 19 THEN 'файлов'",
        "        WHEN x.c % 10 = 1 THEN 'файл'",
        "        WHEN x.c % 10 BETWEEN 2 AND 4 THEN 'файла'",
        "        ELSE 'файлов'",
        "      END),",
        "    b.summary_en=CONCAT('+', x.c, IF(x.c=1, ' file', ' files'))",
        "WHERE b.id=@batch_id;",
        "",
        "-- Drop empty batch if everything was already imported under another source.",
        "DELETE FROM activity_batch",
        "WHERE id=@batch_id",
        "  AND NOT EXISTS (SELECT 1 FROM activity WHERE batch_id=@batch_id LIMIT 1);",
        "",
    ]

    sql_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    man_path.write_text(
        "# dest_name\tsource_path\n"
        + "\n".join(f"{it['file_name']}\t{it['src']}" for it in items)
        + "\n",
        encoding="utf-8",
    )
    miss_path.write_text(
        "\n".join(missing) + ("\n" if missing else ""), encoding="utf-8"
    )
    summary = {
        "source": SOURCE,
        "files_dir": str(files_dir),
        "count": n,
        "missing": len(missing),
        "summary_ru": summary_ru,
        "title_ru": title_ru,
        "items": [
            {
                "book_id": it["book_id"],
                "file_name": it["file_name"],
                "size_kb": it["size_kb"],
                "bytes": it["bytes"],
            }
            for it in items
        ],
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }
    sum_path.write_text(
        json.dumps(summary, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(f"Wrote {sql_path} ({n} books)", file=sys.stderr)
    print(f"Wrote {man_path}", file=sys.stderr)
    print(f"Wrote {sum_path}", file=sys.stderr)
    if missing:
        print(f"Wrote {miss_path} ({len(missing)} missing)", file=sys.stderr)


if __name__ == "__main__":
    main()
